language: go

# Versions of go that are explicitly supported.
go:
 - 1.7.5
 - 1.8
 - tip

# Required for coverage.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

# only one subpackage tested yet
script:
 - go build -a -v ./...
 - diff <(gofmt -d .) <("") 
 - go test -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
